#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../../../environments/${GOOGLE_CLOUD_PROJECT}/.env; 
source ${BASH_SOURCE%/*}/../../../environments/base.env; 
source ${BASH_SOURCE%/*}/.env

source ${GKE_SECRETS_PRODUCTION_FILE}

# manual
# @see https://www.consul.io/docs/agent/encryption.html#gossip-encryption
# 1. install consul from https://www.consul.io/downloads.html
# 2. consul keygen
# 3. add CONSUL_GOSSIP_KEY=xx to production.env
# 4. run this script
# 5. install


kubectl delete secret consul-gossip-key

kubectl create secret generic \
    consul-gossip-key \
    --from-literal=gossip-key=${CONSUL_GOSSIP_KEY} \
    --namespace=${CONSUL_NAMESPACE}

