#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../../../environments/${GOOGLE_CLOUD_PROJECT}/.env; 
source ${BASH_SOURCE%/*}/../../../environments/base.env; 
source ${BASH_SOURCE%/*}/.env

source ${GKE_SECRETS_PRODUCTION_FILE}

kubectl delete secret traefik-dashboard-admin --namespace=${TRAEFIK_NAMESPACE}

FILE=${GCP_DIR}/httpauth

htpasswd -cb ${FILE} admin@${DOMAIN} ${TRAEFIK_PW}

kubectl create secret generic \
    traefik-dashboard-admin \
    --from-file=${FILE} \
    --namespace=${TRAEFIK_NAMESPACE}

rm -f ${FILE}