#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../../../environments/${GOOGLE_CLOUD_PROJECT}/.env; 
source ${BASH_SOURCE%/*}/../../../environments/base.env; 
source ${BASH_SOURCE%/*}/.env

kubectl delete secret ${TRAEFIK_DNS_SA_CREDENTIALS} --namespace=${TRAEFIK_NAMESPACE}

kubectl create secret generic \
    ${TRAEFIK_DNS_SA_CREDENTIALS} \
    --from-file=${TRAEFIK_DNS_SA}.json=${TRAEFIK_DNS_SA_DEST} \
    --namespace=${TRAEFIK_NAMESPACE}