#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../../../environments/${GOOGLE_CLOUD_PROJECT}/.env; 
source ${BASH_SOURCE%/*}/../../../environments/base.env; 
source ${BASH_SOURCE%/*}/.env

# https://cloud.google.com/dns/access-control

# delete
#gcloud iam service-accounts delete \
#    ${TRAEFIK_DNS_SA_EMAIL}

# -------------------
# Create a service account for GCS and GCR that you’ll later be handing to Spinnaker (batch)
gcloud iam service-accounts create \
    ${TRAEFIK_DNS_SA} \
    --project=${GOOGLE_CLOUD_PROJECT} \
    --display-name=${TRAEFIK_DNS_SA}

source ${BASH_SOURCE%/*}/.env

gcloud projects add-iam-policy-binding \
    ${GOOGLE_CLOUD_PROJECT} \
    --role=roles/dns.admin \
    --member=serviceAccount:${TRAEFIK_DNS_SA_EMAIL}

